-- 测试文档数据
INSERT INTO documents (title, content, user_id, category, tags, is_public, view_count) VALUES

-- 技术文档
('Spring Boot 入门教程', '# Spring Boot 入门教程\n\n## 什么是 Spring Boot\n\nSpring Boot 是一个用于快速构建基于 Spring 框架的应用程序的工具。它提供了自动配置、嵌入式服务器和生产就绪特性，使开发人员能够快速启动和运行应用程序。\n\n## 主要特性\n\n- 自动配置\n- 嵌入式服务器（Tomcat、Jetty、Undertow）\n- 生产就绪特性\n- 无代码生成\n- 无 XML 配置\n\n## 快速开始\n\n```java\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) {\n        SpringApplication.run(Application.class, args);\n    }\n}\n```\n\n## 依赖管理\n\nSpring Boot 使用 Maven 或 Gradle 进行依赖管理，通过父项目来管理版本。\n\n```xml\n<parent>\n    <groupId>org.springframework.boot</groupId>\n    <artifactId>spring-boot-starter-parent</artifactId>\n    <version>2.7.14</version>\n</parent>\n```\n\n## 常用启动器\n\n- spring-boot-starter-web\n- spring-boot-starter-data-jpa\n- spring-boot-starter-security\n- spring-boot-starter-test\n\n## 配置文件\n\nSpring Boot 使用 application.properties 或 application.yml 进行配置。\n\n```yaml\nserver:\n  port: 8080\n\nspring:\n  datasource:\n    url: jdbc:mysql://localhost:3306/test\n    username: root\n    password: 123456\n```\n\n## 打包与部署\n\n使用 Maven 打包：\n\n```bash\nmvn clean package\n```\n\n运行应用：\n\n```bash\njava -jar target/myapp.jar\n```\n\n## 监控与管理\n\nSpring Boot Actuator 提供了应用程序的监控和管理功能。\n\n```xml\n<dependency>\n    <groupId>org.springframework.boot</groupId>\n    <artifactId>spring-boot-starter-actuator</artifactId>\n</dependency>\n```\n\n## 总结\n\nSpring Boot 大大简化了 Spring 应用的开发和部署，使开发人员能够专注于业务逻辑而不是配置。它是现代 Java 应用开发的首选框架。', 1, '技术', 'Spring Boot,Java,教程', 1, 528),

-- 前端开发文档
('Vue 3 组件开发最佳实践', '# Vue 3 组件开发最佳实践\n\n## 组件设计原则\n\n- **单一职责**：每个组件只负责一个功能\n- **可复用性**：设计通用的组件接口\n- **可维护性**：清晰的代码结构和命名规范\n- **性能优化**：合理使用 computed 和 watch\n\n## 组件结构\n\n```vue\n<template>\n  <div class="my-component">\n    <h2>{{ title }}</h2>\n    <slot></slot>\n  </div>\n</template>\n\n<script setup>\nimport { ref, computed } from 'vue'\n\ndefineProps({
  title: {
    type: String,
    required: true
  }
})\n\nconst emit = defineEmits(['update'])
</script>\n\n<style scoped>\n.my-component {\n  padding: 20px;\n  border: 1px solid #eaeaea;\n  border-radius: 8px;\n}\n</style>\n```\n\n## Composition API\n\nVue 3 的 Composition API 提供了更灵活的代码组织方式。\n\n```javascript\nimport { ref, computed, onMounted } from 'vue'\n\nexport function useCounter() {\n  const count = ref(0)\n  const doubleCount = computed(() => count.value * 2)\n  \n  function increment() {\n    count.value++\n  }\n  \n  onMounted(() => {\n    console.log('Counter mounted')\n  })\n  \n  return {\n    count,\n    doubleCount,\n    increment\n  }\n}\n```\n\n## 响应式系统\n\nVue 3 使用 Proxy 实现响应式系统，提供了更好的性能和更灵活的 API。\n\n- ref：用于基本类型\n- reactive：用于对象\n- computed：计算属性\n- watch：监听变化\n\n## 组件通信\n\n1. **Props**：父组件向子组件传递数据\n2. **Events**：子组件向父组件传递事件\n3. **Provide/Inject**：跨组件传递数据\n4. **Pinia**：状态管理\n\n## 性能优化\n\n- 使用 `v-memo` 缓存渲染结果\n- 合理使用 `v-if` 和 `v-show`\n- 避免在模板中使用复杂表达式\n- 使用虚拟滚动处理大量数据\n\n## 测试\n\n使用 Vitest 进行组件测试：\n\n```javascript\nimport { mount } from '@vue/test-utils'\nimport MyComponent from './MyComponent.vue'\n\ndescribe('MyComponent', () => {
  it('renders correctly', () => {
    const wrapper = mount(MyComponent, {
      props: {
        title: 'Test Title'
      }
    })
    expect(wrapper.text()).toContain('Test Title')
  })
})
```\n\n## 构建与部署\n\n使用 Vite 进行构建：\n\n```bash\nnpm run build\n```\n\n部署到 Netlify、Vercel 或 GitHub Pages。\n\n## 总结\n\nVue 3 提供了更现代、更灵活的组件开发方式，通过遵循最佳实践，可以构建出高质量的前端应用。', 1, '技术', 'Vue 3,前端,组件', 1, 342),

-- 生活随笔
('旅行见闻：云南之旅', '# 旅行见闻：云南之旅\n\n## 昆明\n\n### 滇池\n\n滇池是云南省最大的淡水湖，被誉为"高原明珠"。站在滇池边，远眺西山，水天一色，景色宜人。\n\n### 石林\n\n石林是世界自然遗产，以其独特的喀斯特地貌闻名。形态各异的石柱仿佛一片石头森林，让人叹为观止。\n\n## 大理\n\n### 洱海\n\n洱海是大理的母亲湖，环湖骑行是最受欢迎的活动。沿途风景如画，蓝天白云，苍山洱海，美不胜收。\n\n### 古城\n\n大理古城保存完好，青石板路、白族建筑、特色小吃，处处体现着白族文化的魅力。\n\n## 丽江\n\n### 丽江古城\n\n丽江古城是世界文化遗产，小桥流水、纳西族风情，夜晚的酒吧街更是热闹非凡。\n\n### 玉龙雪山\n\n玉龙雪山海拔5596米，终年积雪，是纳西族的神山。乘坐缆车登上雪山，仿佛置身仙境。\n\n## 美食\n\n- **过桥米线**：云南特色，鲜美的鸡汤配上各种配料\n- **汽锅鸡**：用特制汽锅烹饪，鸡肉鲜嫩多汁\n- **饵丝**：云南特有的米制品，口感细腻\n- **乳扇**：白族特色，煎制后撒上白糖\n\n## 旅行小贴士\n\n1. 最佳旅游时间：3-5月和9-11月\n2. 高原反应：携带氧气罐\n3. 防晒：紫外线强，注意防晒\n4. 交通：昆明有高铁连接大理、丽江\n5. 住宿：古城内有很多特色客栈\n\n## 感悟\n\n云南的美是多样的，有高原湖泊、喀斯特地貌、民族风情。每一处风景都让人流连忘返，每一种美食都让人回味无穷。这是一次难忘的旅行，期待下次再来。', 1, '生活', '旅行,云南,见闻', 1, 289),

-- 学习笔记
('学习笔记：JavaScript 异步编程', '# 学习笔记：JavaScript 异步编程\n\n## 同步 vs 异步\n\n- **同步**：代码按顺序执行，阻塞后续代码\n- **异步**：代码不阻塞，继续执行后续代码\n\n## 回调函数\n\n最原始的异步处理方式：\n\n```javascript\nfunction fetchData(callback) {\n  setTimeout(() => {\n    callback('Data received')\n  }, 1000)\n}\n\nfetchData((data) => {\n  console.log(data)\n})\n```\n\n## Promise\n\nES6 引入的异步处理方案：\n\n```javascript\nfunction fetchData() {\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      resolve('Data received')\n      // 失败时：reject('Error occurred')\n    }, 1000)\n  })\n}\n\nfetchData()\n  .then(data => console.log(data))\n  .catch(error => console.error(error))\n  .finally(() => console.log('Done'))\n```\n\n## async/await\n\nES8 引入的语法糖，使异步代码看起来像同步代码：\n\n```javascript\nasync function getData() {\n  try {\n    const data = await fetchData()\n    console.log(data)\n    return data\n  } catch (error) {\n    console.error(error)\n  } finally {\n    console.log('Done')\n  }\n}\n\ngetData()\n```\n\n## Promise API\n\n- **Promise.all**：并行执行多个 Promise\n- **Promise.race**：返回第一个完成的 Promise\n- **Promise.allSettled**：等待所有 Promise 完成\n- **Promise.any**：返回第一个成功的 Promise\n\n```javascript\nconst promises = [\n  fetch('url1'),\n  fetch('url2'),\n  fetch('url3')\n]\n\nPromise.all(promises)\n  .then(results => console.log(results))\n  .catch(error => console.error(error))\n```\n\n## 事件循环\n\nJavaScript 的事件循环机制：\n\n1. 执行同步代码\n2. 处理微任务（Promise.then）\n3. 处理宏任务（setTimeout, setInterval）\n\n```javascript\nconsole.log('Start')\n\nsetTimeout(() => console.log('Timeout'), 0)\n\nPromise.resolve().then(() => console.log('Promise'))\n\nconsole.log('End')\n\n// 输出顺序：Start, End, Promise, Timeout\n```\n\n## 异步模式\n\n### 串行执行\n\n```javascript\nasync function serialTasks() {\n  const result1 = await task1()\n  const result2 = await task2(result1)\n  const result3 = await task3(result2)\n  return result3\n}\n```\n\n### 并行执行\n\n```javascript\nasync function parallelTasks() {\n  const [result1, result2, result3] = await Promise.all([\n    task1(),\n    task2(),\n    task3()\n  ])\n  return { result1, result2, result3 }\n}\n```\n\n## 错误处理\n\n### 局部错误处理\n\n```javascript\nasync function handleError() {\n  try {\n    const data = await fetchData()\n    return data\n  } catch (error) {\n    console.error('Error:', error)\n    return null\n  }\n}\n```\n\n### 全局错误处理\n\n```javascript\nprocess.on('unhandledRejection', (error) => {\n  console.error('Unhandled Rejection:', error)\n})\n\nprocess.on('uncaughtException', (error) => {\n  console.error('Uncaught Exception:', error)\n  process.exit(1)\n})\n```\n\n## 总结\n\n异步编程是 JavaScript 的核心特性，掌握 Promise 和 async/await 可以写出更清晰、更可维护的代码。理解事件循环机制有助于解决复杂的异步问题。', 1, '技术', 'JavaScript,异步编程,学习笔记', 1, 412),

-- 工作经验
('项目管理经验分享', '# 项目管理经验分享\n\n## 项目启动\n\n### 需求分析\n\n- 与客户充分沟通，了解业务需求\n- 梳理需求优先级，制定需求文档\n- 进行可行性分析，评估技术风险\n\n### 团队组建\n\n- 根据项目需求选择合适的团队成员\n- 明确角色分工，建立沟通机制\n- 制定团队规则和工作流程\n\n## 项目规划\n\n### 时间规划\n\n- 使用甘特图制定项目时间表\n- 合理分配任务，设置里程碑\n- 预留缓冲时间，应对突发情况\n\n### 资源规划\n\n- 评估所需的人力、物力资源\n- 制定资源分配计划\n- 监控资源使用情况\n\n## 项目执行\n\n### 日常管理\n\n- 每日站会，同步项目进度\n- 定期评审，及时发现问题\n- 使用项目管理工具（如 Jira、Trello）\n\n### 风险控制\n\n- 识别潜在风险，制定应对策略\n- 建立风险预警机制\n- 定期进行风险评估\n\n## 质量管理\n\n### 代码质量\n\n- 制定代码规范，进行代码审查\n- 使用静态代码分析工具\n- 编写单元测试和集成测试\n\n### 交付质量\n\n- 进行功能测试和性能测试\n- 进行用户验收测试\n- 收集用户反馈，持续改进\n\n## 项目收尾\n\n### 交付\n\n- 准备项目文档，包括技术文档、用户手册\n- 进行最终验收，确保项目符合要求\n- 完成项目交接，提供后续支持\n\n### 总结\n\n- 召开项目总结会议，分析项目得失\n- 整理经验教训，形成知识库\n- 对团队成员进行评估和奖励\n\n## 软技能\n\n### 沟通能力\n\n- 与团队成员保持良好沟通\n- 与客户建立有效沟通渠道\n- 及时传递项目信息，避免信息孤岛\n\n### 领导力\n\n- 设定清晰的项目目标\n- 激励团队成员，提高团队凝聚力\n- 处理冲突，维护团队和谐\n\n### 问题解决\n\n- 快速识别问题，制定解决方案\n- 灵活应对变化，调整项目计划\n- 从失败中学习，不断改进\n\n## 工具推荐\n\n- **项目管理**：Jira, Trello, Asana\n- **版本控制**：Git, GitHub, GitLab\n- **文档管理**：Confluence, Notion\n- **沟通工具**：Slack, Microsoft Teams\n- **CI/CD**：Jenkins, GitHub Actions\n\n## 总结\n\n项目管理是一项综合性工作，需要技术知识、管理能力和软技能的结合。通过不断学习和实践，可以提高项目管理水平，确保项目的成功交付。', 1, '工作', '项目管理,经验分享', 1, 376),

-- 健康生活
('健康生活指南', '# 健康生活指南\n\n## 饮食健康\n\n### 均衡饮食\n\n- **蛋白质**：瘦肉、鱼类、豆类、蛋类\n- **碳水化合物**：全谷物、蔬菜、水果\n- **脂肪**：橄榄油、坚果、牛油果\n- **维生素和矿物质**：新鲜蔬菜和水果\n\n### 饮食习惯\n\n- 定时定量，避免暴饮暴食\n- 细嚼慢咽，充分消化\n- 多喝水，保持身体水分\n- 减少加工食品和高糖饮料\n\n## 运动锻炼\n\n### 有氧运动\n\n- 跑步：每周3-5次，每次30分钟\n- 游泳：全身性运动，对关节友好\n- 骑自行车：提高心肺功能\n- 跳绳：高效燃脂运动\n\n### 力量训练\n\n- 哑铃训练：增强肌肉力量\n- 俯卧撑：锻炼上肢和核心\n- 深蹲：锻炼下肢和臀部\n- 平板支撑：增强核心力量\n\n### 柔韧性训练\n\n- 瑜伽：提高柔韧性和平衡能力\n- 拉伸：防止肌肉酸痛和受伤\n- 普拉提：增强核心稳定性\n\n## 作息规律\n\n### 睡眠\n\n- 保持7-8小时的睡眠时间\n- 建立规律的睡眠时间表\n- 睡前避免使用电子设备\n- 创造安静、舒适的睡眠环境\n\n### 休息\n\n- 工作间隙适当休息，避免久坐\n- 定期度假，放松身心\n- 培养兴趣爱好，丰富生活\n\n## 心理健康\n\n### 压力管理\n\n- 深呼吸和冥想\n- 时间管理，避免过度承诺\n- 寻求社会支持，与朋友家人交流\n- 培养积极的心态，学会感恩\n\n### 情绪管理\n\n- 识别和表达情绪\n- 寻找情绪释放的健康方式\n- 培养乐观的思维方式\n- 必要时寻求专业帮助\n\n## 定期体检\n\n- 每年进行一次全面体检\n- 关注家族病史，进行针对性检查\n- 及时接种疫苗\n- 了解自己的健康指标\n\n## 生活环境\n\n- 保持居住环境清洁卫生\n- 室内通风，保持空气新鲜\n- 减少噪音污染\n- 接触大自然，亲近绿色植物\n\n## 健康小习惯\n\n- 每天喝足够的水\n- 保持良好的姿势\n- 避免长时间使用电子设备\n- 定期伸展身体\n- 保持良好的个人卫生\n\n## 总结\n\n健康是人生最宝贵的财富，通过均衡饮食、适量运动、规律作息和良好的心态，可以保持身体和心理的健康。从小事做起，从现在开始，培养健康的生活方式。', 1, '生活', '健康,生活方式', 1, 254),

-- 读书笔记
('《原子习惯》读书笔记', '# 《原子习惯》读书笔记\n\n## 核心概念\n\n- **原子习惯**：微小、持续的行为改变\n- **习惯循环**：提示 → 渴望 → 回应 → 奖励\n- **习惯堆积**：在现有习惯后添加新习惯\n- **环境设计**：改变环境以促进好习惯\n\n## 习惯养成的四大定律\n\n### 第一定律：让它显而易见\n\n- **环境设计**：将提醒放在显眼的位置\n- **习惯堆积**：在现有习惯后添加新习惯\n- **实施意图**：明确何时何地执行习惯\n\n### 第二定律：让它有吸引力\n\n- **喜好绑定**：将不喜欢的习惯与喜欢的事物绑定\n- **加入文化**：与有相同习惯的人一起\n- **视觉化**：想象习惯带来的好处\n\n### 第三定律：让它简单易行\n\n- **减少摩擦**：降低执行习惯的难度\n- **两分钟法则**：将习惯简化为两分钟内可完成\n- **环境准备**：提前准备好所需物品\n\n### 第四定律：让它令人满足\n\n- **即时奖励**：完成习惯后给予奖励\n- **追踪进度**：记录习惯执行情况\n- **习惯契约**：与他人建立问责机制\n\n## 习惯养成的策略\n\n### 身份认同\n\n- **改变自我形象**：从"我想减肥"到"我是健康的人"\n- **小赢策略**：通过小成就强化身份认同\n- **行为与身份一致**：让行为符合你想成为的人\n\n### 习惯追踪\n\n- **记录进度**：使用习惯追踪器\n- **避免中断**：保持习惯链不中断\n- **定期回顾**：每周回顾习惯执行情况\n\n### 习惯自动化\n\n- **环境触发**：设置环境提示\n- **减少决策**：将习惯变成自动化行为\n- **习惯叠加**：利用现有习惯触发新习惯\n\n## 克服习惯障碍\n\n### 缺乏动力\n\n- **从小处开始**：从微小的改变开始\n- **关注过程**：关注习惯本身而不是结果\n- **环境设计**：让好习惯更容易执行\n\n### 缺乏时间\n\n- **两分钟法则**：将习惯简化为两分钟\n- **习惯堆积**：在现有习惯后添加新习惯\n- **优先级**：将习惯放在重要位置\n\n### 缺乏意志力\n\n- **环境设计**：减少诱惑，增加提示\n- **习惯自动化**：减少需要意志力的决策\n- **循序渐进**：逐步增加习惯难度\n\n## 高级策略\n\n### 习惯叠加\n\n```\n在[现有习惯]之后，我将[新习惯]\n```\n\n例如："在我倒完咖啡后，我将做10个俯卧撑。"\n\n### 习惯追踪\n\n- 使用日历或应用记录习惯\n- 标记完成的习惯，形成视觉反馈\n- 定期回顾，调整策略\n\n### 习惯环境\n\n- **提示**：放在显眼位置\n- **工具**：准备好所需物品\n- **触发**：设置明确的触发点\n\n## 实际应用\n\n### 健康习惯\n\n- 每天喝8杯水\n- 每天运动30分钟\n- 每天吃水果和蔬菜\n\n### 学习习惯\n\n- 每天阅读30分钟\n- 每天学习新技能1小时\n- 每天写学习笔记\n\n### 工作习惯\n\n- 每天早上规划任务\n- 每工作50分钟休息10分钟\n- 每天总结工作成果\n\n## 总结\n\n《原子习惯》提供了一套科学、实用的习惯养成方法。通过微小的改变，持续的积累，我们可以逐渐成为更好的自己。关键在于理解习惯的原理，运用四大定律，设计适合自己的习惯系统。', 1, '学习', '读书笔记,习惯养成', 1, 398);
